### ISSUE TITLE
Scaling/Reactiveness

### ISSUE THREAD

**Issue by sallykeating** [distributedID/blockchain-explorer#98]

**Comment by agarwalakarsh** [comment]
Looks like, we can overhaul our own UI, with a little bit of a change in the packages we import. Hence, I'm creating a new branch of `83-...` branch to get it set up and start working on a demo UI, to see if we can improve on our Dashboard.

**Comment by agarwalakarsh** [comment]
Covered in the `98-akarsh-...` branch.
